### ISSUE TITLE
Copyright and license

### ISSUE THREAD

**Issue by jonasmalacofilho** [SmilyOrg/ansi#2]
I would like to use this (or, more specifically, a variant of this) in an open-source project.

Is this code open-source and, if so, can you add copyright and license information to the repository?

**Comment by SmilyOrg** [comment]
Yeah, of course, thanks for asking / reminding me that it was unlicensed! Added the MIT license now. Just asking out of interest, what kind of changes did you make in your variant? :)

**Comment by jonasmalacofilho** [comment]
Thanks!  : )

I needed to support Node.js and to leave the availability checking to runtime; in the end I made a quick and dirty variant that only supports colors/bold...

I'll submit the changes for Node.js support in a pull request in a few minutes.
